### ISSUE TITLE
Suspicious skill calculation

### ISSUE THREAD

**Issue by jkisor** [amoeba/accharplanner#387]
A player is suspicious of the planner's calculated summoning value. (Levistras discord: https://discordapp.com/channels/601796734129012766/601815169416429587/979998459723657246)

"the character planner is incorrectly adding up stats if you "Aug" your attributes. It's doubling them. At least for Willpower Aug it is. I'm finding this out the hard way as I just flipped my build around and i'm short 9-10 points on several skills 😦 I don't want somebody else to make the same mistake."
"As you can see, with the Self Aug'd to 60 pts. It gives an extra 13 pts of summoning. Which is incorrect!"

![unknown](https://user-images.githubusercontent.com/1517368/170827581-06b0bfd0-f1c4-4d05-9c50-c8536c2a139e.png)

**Comment by amoeba** [comment]
Thans for reporting @jkisor, I'l have a look.

**Comment by amoeba** [comment]
I see that something's going on but it's not clear to me how the double-counting is happening. Still looking at it.
