### ISSUE TITLE
Recklessness Skill display formula is incorrect

### ISSUE THREAD

**Issue by jkisor** [amoeba/accharplanner#392]
The view says "(S+Q)/2" for the Recklessness skill.

The calculation is divided by 3 instead of 2 though: https://github.com/amoeba/accharplanner/blob/0b333aa3ec08a78e1ec85b4f5b37af10c1704dc9/src/store/getters.ts#L1911

Wiki says that it's (Strength + Quickness) / 3: http://acpedia.org/wiki/Recklessness

I believe the only change needed is here:
https://github.com/amoeba/accharplanner/blob/0b333aa3ec08a78e1ec85b4f5b37af10c1704dc9/src/mappings.ts#L97

Found via Levistras Discord: https://discord.com/channels/601796734129012766/601815169416429587/1001582716195717141

**Comment by amoeba** [comment]
Thanks a ton @jkisor. Fixed and deployed to https://planner.treestats.net. My take a minute for caches to update.
